# The recommended basic settings for GNN
out_dir: results
dataset:
  format: PyG
  name: TU_PROTEINS
  # other datasets: Cora, CiteSeer, PubMed, TU_PROTEINS, TU_ENZYMES
  task: link_pred
  task_type: classification
  transductive: True
  split: [0.8, 0.2]
  augment_feature: []
  augment_feature_dims: [0]
  augment_feature_repr: position
  augment_label: ''
  augment_label_dims: 0
train:
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 256
  stage_type: stack
  batchnorm: True
  act: prelu
  dropout: 0.0
  agg: add
  normalize_adj: False
optim:
  max_epoch: 200
neuroevolution:
  optimizers: [sgd, rmsprop, adam]
  layer_types: [linear, mlp, gcnconv, sageconv, gatconv, ginconv, generalconv]
  transforms: [ego, none]
  batch_sizes: [1, 16, 32, 64, 128, 256, 512, 1024]
  lrs:
    min: 0.00001
    max: 1.0
  resample_negatives: [True, False]
  model_edge_decoding: [dot, cosine_similarity, concat]
  model_graph_pooling: [add, mean, max]
  gnn_keep_edge:
    min: 0.1
    max: 0.9
  gnn_att_heads: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]